### ISSUE TITLE
不能正确加载列表和主题

### ISSUE THREAD

**Issue by john5du** [kucial/v2ex-react-native#1]
设备：14pm 
系统：16.0.2
![image](https://user-images.githubusercontent.com/45614150/194534943-42dd743c-c70d-435e-bed0-3db1834ef04e.png)
![image](https://user-images.githubusercontent.com/45614150/194535090-cf899bd2-f551-452a-acf5-9c4e12f43ec0.png)

**Comment by kongkx** [comment]
方便点一下 “右上角... ，使用 内部webview 打开” ，然后也截个图？

**Comment by john5du** [comment]
这样看应该是2fa的问题吧
![image](https://user-images.githubusercontent.com/45614150/194543775-66331a99-5684-4ddc-ad29-73df2b49c977.png)

**Comment by kongkx** [comment]
好的，我看看怎么处理
