### ISSUE TITLE
回复重复出现

### ISSUE THREAD

**Issue by A13xMogh** [kucial/v2ex-react-native#11]
1.8.2版本，iOS15.6，iPhone13 mini

前几楼的回复会在下面重复出现，导致覆盖后面真正的回复。

![FF93CEE7-BEEA-4863-A35B-0C4E65D38770](https://github.com/kucial/v2ex-react-native/assets/116833727/baaeef73-d66e-41de-ad22-6f32153aedca)

**Comment by kongkx** [comment]
我看看是什么情况

A13xMogh ***@***.***> 于2023年12月2日周六 09:25写道：

**Comment by kongkx** [comment]
已经在新发布的版本 1.8.3 修复.
